name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - run: yarn install

      - run: yarn test

      - run: yarn format-check
      
      - run: yarn lint
